name: qa_module
description: A quality assurance tool for generating documentation and tests.
version: 1.0.0
publish_to: none
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2
  http: ^1.2.2
  redis: ^4.0.0
  yaml: ^3.1.2
  process_run: ^0.14.2
  analyzer: ^6.8.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  ffi: ^2.0.1
  sample_repo:
    path: ./example/sample_repo

dev_dependencies:
  test: ^1.25.8
